detect when ExtendedStatus is not enabled, fixed return code.
git-svn-id: svn+ssh://svn.isvtec.com/var/lib/subversion/admin/nagios-plugins-cyb@1296 63a8e5df-aab3-48d7-8c8d-b200f9e8f67e

diff --git a/plugins/check_long_lasting_apache_queries b/plugins/check_long_lasting_apache_queries
--- a/plugins/check_long_lasting_apache_queries
+++ b/plugins/check_long_lasting_apache_queries
@@ -25,18 +25,34 @@ then
 fi
 
 url=http://localhost/server-status
-rc=0
 
-w3m -dump $url \
-    | awk '/ W / {print $6" "$13" "$14}' \
+tempfile=$(tempfile)
+trap "rm -f $tempfile" 0 1 2 5 15
+
+# Check if server-status is available
+if ! w3m -cols 150 -dump $url > $tempfile 2>/dev/null
+then
+    echo "Error while accessing $url"
+    exit 2
+fi
+
+# Check if ExtendedStatus is enabled
+if grep -qF 'you need to use the ExtendedStatus On directive.' $tempfile
+then
+    echo "Unable to fetch Apache info, please enable ExtendedStatus"
+    exit 2
+fi
+
+# Parse server-status output
+awk '/ W / {print $6" "$13" "$14}' $tempfile \
     | while read time_elapsed_for_request vhost uri
 do
     if [ "$time_elapsed_for_request" -gt "$max_elapsed_time" ]
     then
-	rc=2
-	echo -n "http://$vhost$uri is lasting for ${time_elapsed_for_request}s. "
+	echo "http://$vhost$uri is lasting for ${time_elapsed_for_request}s. "
+	exit 2
     fi
 done
 
-echo
-exit $rc
+echo OK
+exit 0
