plugins/check_df: correctly check the return code of 'tempfile' and return the output and error code to Nagios.

diff --git a/plugins/check_df b/plugins/check_df
--- a/plugins/check_df
+++ b/plugins/check_df
@@ -35,7 +35,13 @@ then
 fi
 
 # Fetch disk usage data
-tempfile=$(tempfile)
+tempfile=$(tempfile 2>&1 || true)
+if [ ! -f "$tempfile" ]
+then
+    echo "Unable to create temporary file: $tempfile"
+    exit 2
+fi
+
 trap "rm -f $tempfile" EXIT HUP INT TRAP TERM
 
 (
