check_raid: Typo in tw_cli.
git-svn-id: svn+ssh://svn.isvtec.com/var/lib/subversion/admin/nagios-plugins-cyb@1778 63a8e5df-aab3-48d7-8c8d-b200f9e8f67e

diff --git a/plugins/check_raid b/plugins/check_raid
--- a/plugins/check_raid
+++ b/plugins/check_raid
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #
 # Copyright (C) 2011 Cyril Bouthors <cyril@bouthors.org>
 #
@@ -77,9 +77,9 @@ fi
 # Check 3w_xxxx RAID
 if grep -wFq 3w_xxxx /proc/modules
 then
-    if ! which tw_cli >/dev/null
+    if ! which tw-cli >/dev/null
     then
-	echo "$0: unable to find tw_cli"
+	echo "$0: unable to find tw-cli"
 	exit 2
     fi
     for status in $(tw-cli /c0 show | awk '/^u/ {print $3}')
