#52169 use celery to ping worker

diff --git a/plugins/check_celery_ping b/plugins/check_celery_ping
--- a/plugins/check_celery_ping
+++ b/plugins/check_celery_ping
@@ -18,22 +18,23 @@
 
 worker=$1
 app_dir=$2
+app=$3
 
 set -e -o pipefail -o nounset
 
 rc=0
 
 # Check arguments
-if [ -z "$worker" -o -z "$app_dir" ]
+if [ -z "$worker" -o -z "$app_dir" -o -z "$app" ]
 then
-    echo "Usage: $0 WORKER APP_DIR"
+    echo "Usage: $0 WORKER APP_DIR APP"
     exit 3
 fi
 
-# Check if $app_dir/manage.py exists
-if [ ! -e "$app_dir/manage.py" ]
+# Check if $app_dir/$app/celery.py exists
+if [ ! -e "$app_dir/$app/celery.py" ]
 then
-    echo "Cannot find any manage.py file in APP_DIR variable directory"
+    echo "Cannot find any $app_dir/$app/celery.py"
     exit 3
 fi
 
@@ -42,7 +43,7 @@ tempfile=$(tempfile)
 trap "rm -f $tempfile" EXIT HUP INT TRAP TERM
 
 # Ping Celery
-if ! $app_dir/manage.py celery inspect ping -d $worker > $tempfile 2>&1
+if ! celery -A "$app" --workdir="$app_dir" inspect ping -d $worker > $tempfile 2>&1
 then
     rc=2
 fi
