#49376 cosmetic

diff --git a/plugins/check_syslog b/plugins/check_syslog
--- a/plugins/check_syslog
+++ b/plugins/check_syslog
@@ -18,13 +18,13 @@
 set -e -o pipefail -o nounset
 msg='Syslog test'
 
-SOCKET_ERROR='--socket-errors=on'
+socket_error='--socket-errors=on'
 if dpkg -l bsdutils | grep -qF '2.20'
 then
     SOCKET_ERROR=''
 fi
 
-if ! timeout 5 logger -i -t $0 -d -p local0.alert $SOCKET_ERROR $msg 2>&1
+if ! timeout 5 logger -i -t $0 -d -p local0.alert "$socket_error" $msg 2>&1
 then
     exit 2
 fi
